### ISSUE TITLE
linux - needs "-lpthread"

### ISSUE THREAD

**Issue by rotten** [teammcr192/super-resolution#2]
In order to get the code to build on Ubuntu 18.04 I had to add **pthread** to the **target_link_libraries()** in **CMakeLists.txt** .

Otherwise **make** throws this:
`/usr/bin/x86_64-linux-gnu-ld: CMakeFiles/Test.dir/test/test_image_model.cpp.o: undefined reference to symbol 'pthread_setspecific@@GLIBC_2.2.5'`

(It seemed like too much work to fork and PR for a one-word update - plus I don't know if that will break something on Mac since I don't have one of those to test with.)

**Comment by jodyngo** [comment]
I have got similar error as below, kindly help advise me on this issue

/usr/bin/ld: CMakeFiles/Test.dir/test/test_image_model.cpp.o: undefined reference to symbol 'pthread_setspecific@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/Test.dir/build.make:404: recipe for target 'bin/Test' failed
make[2]: *** [bin/Test] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Test.dir/all' failed
make[1]: *** [CMakeFiles/Test.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rotten** [comment]
In *CMakeLists.txt* add pthread to this block of code:
```
 74 target_link_libraries(
 75   Test
 76   LibSuperResolution
 77   glog
 78   gflags
 79   gmock
 80   gmock_main
 81   gtest
 82   gtest_main
 83   m
 84   pthread
 85   ${OpenCV_LIBS}
 86 )
```
^ the numbers are line numbers.

**Comment by jodyngo** [comment]
> In _CMakeLists.txt_ add pthread to this block of code:
> 
> ```
>  74 target_link_libraries(
>  75   Test
>  76   LibSuperResolution
>  77   glog
>  78   gflags
>  79   gmock
>  80   gmock_main
>  81   gtest
>  82   gtest_main
>  83   m
>  84   pthread
>  85   ${OpenCV_LIBS}
>  86 )
> ```
> 
> ^ the numbers are line numbers.

Thank you.
